<?xml version="1.0" encoding="utf-8"?><Database Name="QLDACNTT" Class="dbChessContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-MGN3IP8\SQLEXPRESS;Initial Catalog=QLDACNTT;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QLDACNTTConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.NGUOICHOI" Member="NGUOICHOIs">
    <Type Name="NGUOICHOI">
      <Column Name="MANC" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNC" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="IDTAIKHOAN" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="MAPHONG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PHONG_NGUOICHOI" Member="PHONG" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="PHONG" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="TAIKHOAN_NGUOICHOI" Member="TAIKHOAN" ThisKey="IDTAIKHOAN" OtherKey="IDTAIKHOAN" Type="TAIKHOAN" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHONG" Member="PHONGs">
    <Type Name="PHONG">
      <Column Name="MAPHONG" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENPHONG" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Association Name="PHONG_NGUOICHOI" Member="NGUOICHOIs" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="NGUOICHOI" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="IDTAIKHOAN" Type="System.String" DbType="Char(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATKHAU" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="HO" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TEN" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="Char(40)" CanBeNull="true" />
      <Association Name="TAIKHOAN_NGUOICHOI" Member="NGUOICHOIs" ThisKey="IDTAIKHOAN" OtherKey="IDTAIKHOAN" Type="NGUOICHOI" />
    </Type>
  </Table>
</Database>